# Generated by Django 3.0.8 on 2020-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200728_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='photo 95.jpeg', upload_to=''),
        ),
    ]
