# Generated by Django 3.0.8 on 2020-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Government', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_visited',
            field=models.DateField(auto_now_add=True),
        ),
    ]
